services:
  backend:
    build : ./backend
    image: day4-backend
    container_name: day4-backend
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: day4-nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
